name: 💡 功能建议 / 规则库扩充
description: 提议支持新的流氓 Office 加载项类型或工具优化建议
title: "【需求/建议】: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        欢迎为 Remove-OfficePlus 贡献新的流氓插件查杀规则或功能建议！
  - type: textarea
    id: feature_desc
    attributes:
      label: 建议或需求描述
      description: 请清晰描述希望增加的功能或需要支持查杀的插件名称
    validations:
      required: true
